import {
  LuMic,
  LuMicOff,
  LuVideo,
  LuVideoOff,
  LuVolume2,
  LuVolumeX,
  LuScreenShare,
  LuScreenShareOff,
  LuPhone,
  LuPhoneOff,
  LuPlay,
  LuPause,
  LuCircleStop,
  LuCircleDot,
  LuUsers,
  LuUser,
  LuUserPlus,
  LuHand,
  LuMessageSquare,
  LuMessagesSquare,
  LuSend,
  LuSmile,
  LuPaperclip,
  LuChevronUp,
  LuChevronDown,
  LuChevronLeft,
  LuChevronRight,
  LuMenu,
  LuArrowLeft,
  LuArrowRight,
  LuPlus,
  LuMinus,
  LuCheck,
  LuX,
  LuPencil,
  LuTrash,
  LuSettings,
  LuSearch,
  LuFilter,
  LuBell,
  LuLogOut,
  LuLogIn,
  LuRefreshCw,
  LuInfo,
  LuTriangleAlert,
  LuCircleCheck,
  LuCircleX,
  LuLoader,
  LuEye,
  LuEyeOff,
  LuCopy,
  LuLink,
  LuCalendar,
  LuClock,
  LuGlobe,
  LuMoon,
  LuSunDim,
} from "react-icons/lu";
import { AhLogo } from "@ah/components/utils/Svg";

export const iconMap = {
  mic: LuMic,
  "mic-off": LuMicOff,
  camera: LuVideo,
  "camera-off": LuVideoOff,
  volume: LuVolume2,
  "volume-off": LuVolumeX,
  "screen-share": LuScreenShare,
  "screen-share-off": LuScreenShareOff,

  call: LuPhone,
  "call-end": LuPhoneOff,
  play: LuPlay,
  pause: LuPause,
  stop: LuCircleStop,
  record: LuCircleDot,

  users: LuUsers,
  user: LuUser,
  "user-add": LuUserPlus,
  hand: LuHand,

  chat: LuMessageSquare,
  chats: LuMessagesSquare,
  send: LuSend,
  emoji: LuSmile,
  attach: LuPaperclip,

  "chevron-up": LuChevronUp,
  "chevron-down": LuChevronDown,
  "chevron-left": LuChevronLeft,
  "chevron-right": LuChevronRight,
  menu: LuMenu,
  "arrow-left": LuArrowLeft,
  "arrow-right": LuArrowRight,

  plus: LuPlus,
  minus: LuMinus,
  check: LuCheck,
  close: LuX,
  edit: LuPencil,
  delete: LuTrash,

  settings: LuSettings,
  search: LuSearch,
  filter: LuFilter,
  bell: LuBell,
  logout: LuLogOut,
  login: LuLogIn,
  refresh: LuRefreshCw,

  info: LuInfo,
  warning: LuTriangleAlert,
  success: LuCircleCheck,
  error: LuCircleX,
  loading: LuLoader,

  eye: LuEye,
  "eye-off": LuEyeOff,
  copy: LuCopy,
  link: LuLink,
  calendar: LuCalendar,
  clock: LuClock,
  glob: LuGlobe,
  sun: LuSunDim,
  moon: LuMoon,
  "ah-logo": AhLogo,
} as const;

export type IconName = keyof typeof iconMap;
